### ISSUE TITLE
iOS12 切换进度条加载菊花不消失

### ISSUE THREAD

**Issue by Songkunda** [Chimeejs/chimee-plugin-mobile-controlbar#7]
在iphone6 6s 6p升级iOS12后 切换进度条视频继续播放但加载菊花不消失 暂停再次播放才消失
11.4 10.3 均正常

**Comment by yandeqiang** [comment]
之前使用 playing 事件来做 loading  的结束， 新增加了 seeked 来做 loading 结束的判断
